[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
adwiser = "HBUba6LqBPZSh2QNGwVDFxVq1vaj9Sav9vhVoAt1Ti6w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/vasi/myGitHub/Turbin3/adwiser/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"